"""PlatformIO pre-build script: embeds data/*.html gzip-compressed into include/web_pages.h.

The pages are edited as normal files in data/ and are uploaded together with the
firmware, so there is no separate filesystem upload.
"""
import gzip
import os

Import("env")  # noqa: F821 - provided by PlatformIO

project_dir = env.subst("$PROJECT_DIR")  # noqa: F821
data_dir = os.path.join(project_dir, "data")
out_path = os.path.join(project_dir, "include", "web_pages.h")


def c_name(filename):
    return "PAGE_" + "".join(ch if ch.isalnum() else "_" for ch in filename).upper()


def generate():
    files = sorted(f for f in os.listdir(data_dir) if f.endswith(".html"))
    lines = [
        "// Generated by scripts/embed_web.py from data/ - do not edit",
        "#pragma once",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "struct EmbeddedPage {",
        "  const char *name;",
        "  const uint8_t *data;",
        "  size_t len;",
        "};",
        "",
    ]
    for filename in files:
        with open(os.path.join(data_dir, filename), "rb") as f:
            # mtime=0 keeps the output identical for identical input
            packed = gzip.compress(f.read(), compresslevel=9, mtime=0)
        lines.append("static const uint8_t %s[] = {" % c_name(filename))
        for i in range(0, len(packed), 20):
            lines.append("  " + ", ".join("0x%02x" % b for b in packed[i:i + 20]) + ",")
        lines.append("};")
        lines.append("")
    lines.append("static const EmbeddedPage EMBEDDED_PAGES[] = {")
    for filename in files:
        lines.append('  {"%s", %s, sizeof(%s)},' % (filename, c_name(filename), c_name(filename)))
    lines.append("};")
    lines.append("")
    content = "\n".join(lines)

    # Rewrite only on change, so unchanged pages do not trigger a rebuild
    old = None
    if os.path.exists(out_path):
        with open(out_path) as f:
            old = f.read()
    if content != old:
        with open(out_path, "w") as f:
            f.write(content)
        print("embed_web: generated %s from %d pages" % (os.path.relpath(out_path, project_dir), len(files)))


generate()
